[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.42.0", features = ["full"] }
axum = { version = "0.8.1", features = ["ws"] }
futures-util = "0.3.31"
tower-http = { version = "0.6.2", features = ["cors"] }
